### ISSUE TITLE
Add AWS Stats for reporting

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#10]
We want:

* to have a clear visual aid of how much data is in the sitedata at what sizes
* want to see where the current target cut off is for the S3 threshold
* have an easy estimate of how much money you'd save by pushing data to s3

Tasks:
* [ ] add a cost per byte for local disc in settings (default to apples to apples aws current price)
* [ ] add a cost per byte for s3 in settings (default to real cost)
* [ ] Show a table which columns like this:

S3 cutoff | Savings in mB | Saving in $ |  2 env's | 3 envs
--- | -- | -- | ---- | --
0 |  0 mB | $0 | $0 | $0
1 mB | 100mB | $10 | $20 | $30
10 MB |  1000 mB | $1000 | $2000 | $3000
20 MB |  2000 mB | $2000 | $4000 | $6000

It should show one row for each progressively bigger file size up to the size of files in this db, and at least one extra row for good luck

**Comment by kenneth-hendricks** [comment]
Starting query:
select log logindex, sum(filesize) totalsize, count(*) filecount from (select distinct contenthash, filesize, floor(log(2,filesize) * 4) as log from mdl_files where filesize != 0) d group by log order by log;

**Comment by brendanheywood** [comment]
Would be good to also break that query down by mimetype, I'd cut all the mimetypes in half to get the main doc type with some small tuning (need to add mimetype for backups):

```
$ SELECT sum(filesize),
      filetype                    
FROM (SELECT 
        filesize,
              
CASE                      
    WHEN mimetype = 'application/pdf' THEN 'pdf'
    WHEN mimetype = 'application/epub+zip' THEN 'epub'
    ELSE         substr(mimetype,        0,
        strpos(mimetype, '/')) 
END AS filetype
FROM mdl_files
WHERE mimetype IS NOT NULL
) stats
GROUP BY filetype
ORDER BY
sum(filesize),
filetype
;
     sum      |  filetype   
--------------+-------------
     10155878 | epub
    126273096 | message
   2222192208 | text
  13654953978 | document
  48197708360 | image
  84579763927 | audio
 657387267935 | pdf
 710310145031 | video
 880515700813 | application

```

but

**Comment by brendanheywood** [comment]
We have enough stats to see what is going on, I've just made them a little prettier. I think this is enough
