### ISSUE TITLE
performance - SQL having clause

### ISSUE THREAD

**Issue by egiles** [catalyst/moodle-tool_objectfs#106]
[query_plans.docx](https://github.com/catalyst/moodle-tool_objectfs/files/2421955/query_plans.docx)
In our instance we have > 15.6 Million rows in mdl_files and only ~3.6 Million actual files.

By moving (most) filters from the HAVING clause to a WHERE there is significant performance increase in the queries. For example we currently have 5 minutely upload check with max runtime of 4. One of the reports that runs each 5 minutes takes 1.3 minutes to run and >700MB temp table. Refactoring it runs in 4secs and tiny footprint. 

I will upload a doc file in a second with EXPLAIN ANALYSE results to help visualise whats happening.

**Comment by mattporritt** [comment]
@egiles are you able to provide the document you have referenced?

**Comment by egiles** [comment]
yeah, it's attached in the description... https://github.com/catalyst/moodle-tool_objectfs/files/2421955/query_plans.docx

**Comment by dmitriim** [comment]
The issue was partly fixed in https://github.com/catalyst/moodle-tool_objectfs/pull/119

More work is required to fix all SQLs

**Comment by brendanheywood** [comment]
Fixed in https://github.com/catalyst/moodle-tool_objectfs/pull/175
