### ISSUE TITLE
Any plans to update to 3.5 and 3.6

### ISSUE THREAD

**Issue by joaocc** [catalyst/moodle-tool_objectfs#123]
Hi,
Are there any plans to update the plugin to work with Moodle 3.5 and 3.6?
Thx

**Comment by ilya-catalyst** [comment]
> Hi,
> Are there any plans to update the plugin to work with Moodle 3.5 and 3.6?
> Thx

Hi joaocc,

The plugin is working with Moodle 3.5. Could you please specify what exact problem do you have?

Thanks,
Ilya

**Comment by joaocc** [comment]
Hi,
I didn't try it yet. The question was because 3.5 is not mentioned in moodle plugins portal.
Thx

**Comment by synesthesia** [comment]
HI, similar question. Installed on 3.6, checks pass and I can see the test files in the Azure blob. However a test file uploaded into a course which is big enough to meet the criteria (which are set to  min size 1kb, min age 1 second for testing) is not getting transferred to the blob

**Comment by danmarsden** [comment]
Hi @synesthesia - our ability to provide support configuring and using the plugins is quite limited - (unless you would like to pay for commercial support) - the best thing I can suggest is to make sure you are running cron.

**Comment by synesthesia** [comment]
HI @danmarsden appreciate that as this is OSS. :-)

Scheduled crons definitely running, I'm going to change config to use AWS S3 instead to try and isolate the behaviour.

I might be open to paid support as this is for a commercial site, where do I find the contact for that please?

**Comment by brendanheywood** [comment]
hi @synesthesia please contact us: https://www.catalyst-au.net/content/contact-us

Also I'll close this issue as we do already support 3.5 and 3.6.
