### ISSUE TITLE
Add support for DigitalOcean Spaces (S3 compatible object storage)

### ISSUE THREAD

**Issue by kisonay** [catalyst/moodle-tool_objectfs#128]
Would you be open to merging a PR that enables this option? It uses the S3 SDK so it would be relatively minor changes.

**Comment by brendanheywood** [comment]
Yes :)

**Comment by kisonay** [comment]
do you want to create a new branch or target master?

**Comment by brendanheywood** [comment]
It usually works best if you create a new branch against master in your forked repo and github magic makes the rest easy

**Comment by kisonay** [comment]
Yes, that is what I did, I just didn't know which branch you wanted me to target for the PR.

**Comment by kisonay** [comment]
New pull request submitted: https://github.com/catalyst/moodle-tool_objectfs/pull/130

**Comment by kenneth-hendricks** [comment]
Merged,

Thanks @kisonay
