### ISSUE TITLE
update clientnotavailable string

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#131]
Text reads as

'The configured client \'{$a}\' is not available. Please install the required dependencies.'

which is misleading as it is not necessarily the configured client.

Should read 

'The \'{$a}\' client is not available. Please install the required dependencies if this is the desired object storage client.'

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/moodle-tool_objectfs/pull/183
