### ISSUE TITLE
Nothing recorded on S3

### ISSUE THREAD

**Issue by devashish-laitkor** [catalyst/moodle-tool_objectfs#133]
Hi,

I have setup this plugin, and add all credentials, But not found any file  syncing on amazon S3. 
https://nimb.ws/54mRPp

Also no any report generated. 
https://nimb.ws/3TgjUZ

Can you help us out.

**Comment by danmarsden** [comment]
Hi @devashish-laitkor, Please make sure you read the docs and have cron running on your system:
https://github.com/catalyst/moodle-tool_objectfs#moodle-configuration

alternatively feel free to get back in touch if you would like commercial level support - thanks!
