### ISSUE TITLE
file permission - unit test failed 

### ISSUE THREAD

**Issue by tuanngocnguyen** [catalyst/moodle-tool_objectfs#134]
Hi,

I got unit test failure:

1) tool_objectfs\tests\object_file_system_testcase::test_get_local_path_from_hash_fetch_remote_will_restore_file_permissions
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'666'
+'0666'

/var/www/site/admin/tool/objectfs/tests/object_file_system_test.php:87
/var/www/site/lib/phpunit/classes/base_testcase.php:600
/var/www/site/lib/phpunit/classes/advanced_testcase.php:68

To re-run:
 vendor/bin/phpunit tool_objectfs\tests\object_file_system_testcase admin/tool/objectfs/tests/object_file_system_test.php

Environment:
PHP: 7.2.17.0.0.18.04.1, pgsql: 9.6.13, OS: Linux 4.4.0-148-generic x86_64
PHPUnit 7.5.11 by Sebastian Bergmann and contributors.

**Comment by kristian-94** [comment]
You only see this issue in moodle 3.7 is that right? Looks like moodle have made some subtle change to file permissions in the latest version.

**Comment by kristian-94** [comment]
Scratch that, it looks like this error is fixed by the latest version of the plugin. Have you tried the latest version @tuanngocnguyen  ?

**Comment by tuanngocnguyen** [comment]
Thanks @kristian-94, It seems to be fixed.
