### ISSUE TITLE
Reduce lock waiting when run cron task

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_objectfs#140]
When we process candidates we check for the locks each time and wait for 600 seconds. Probably we don't need to wait that long.

**Comment by golenkovm** [comment]
Hey @brendanheywood 
What do you think about moving it to config? Let it be a variable with default value 0.

**Comment by brendanheywood** [comment]
I would never wait at all, the only reason there would ever be an existing lock is if another process is doing the same thing as what this process is wanting to do. So just set it to zero and ignore it and move on. If there is something valid that needs to be done then it will get picked up on the next cron tick. I don't think config has any real value either, this should not be something you would ever want to tune to non-zero

**Comment by golenkovm** [comment]
Changes after discussion:
- Remove lock waiting when run cron task.
- Add lock timing and status logging if the plugin has logging turned on.
- Add a test to acquire a lock if object is not locked.

Merged into master.
