### ISSUE TITLE
Duplicate records error when running  task/delete_local_objects

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_objectfs#144]
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: ++ Did you remember to make the first column something unique in your call to get_records? Duplicate value 'da39a3ee5e6b4b0d3255bfef95601890afd80709' found in column 'contenthash'. ++
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 138 of /admin/tool/objectfs/classes/object_manipulator/manipulator.php: call to pgsql_native_moodle_database->get_records_sql()
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 182 of /admin/tool/objectfs/classes/object_manipulator/manipulator.php: call to tool_objectfs\object_manipulator\manipulator->get_candidate_objects()
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 52 of /admin/tool/objectfs/classes/task/delete_local_objects.php: call to tool_objectfs\object_manipulator\manipulator::setup_and_run_object_manipulator()
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 105 of /lib/cronlib.php: call to tool_objectfs\task\delete_local_objects->execute()
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 67 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
Jun  5 07:05:03 754e2426b1e9 ecs_monash_35_moodle_uat: * line 61 of /admin/cli/cron.php: call to cron_run()

**Comment by golenkovm** [comment]
PR #157 merged into master.
