### ISSUE TITLE
Simply the settings to only show settings for the store in use

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#151]
In hind site we should have done this as subplugins, but I think we'll just continue as is for now.

What I want to see on the settings page is:

1) [ ] if $CFG->alternative_file_system_class is empty then show a simple warning which says it must be set and how to set it. Don't show anything else.

2) [ ] If $CFG->alternative_file_system_class is set, then parse out the name of the storage and auto load an class which appends details to the settings_form object

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/moodle-tool_objectfs/pull/183
