### ISSUE TITLE
Clean up the class stucture and align against stores

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#152]
1) [ ] moodle wants all local classes to be inside /classes/local - but we are already assuming classes like /classes/azure_file_system.php and exactly in that path so leave just those there so we don't break backwards compat. Log, privacy, task should remain as they are 'moodle' classes not local

2) [ ] move everything into a store subdirectory and then a folder for each store, eg

/classes/azure/ => /classes/local/store/azure/

/classes/client/azure_client.php => /classes/local/store/azure/client.php

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/moodle-tool_objectfs/pull/183
