### ISSUE TITLE
Refactor all the define_*_check functions into a shared base class

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#155]
eg define_amazon_s3_check

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/client/s3_client.php#L269

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/client/do_client.php#L72

As well as define_azure_check and define_swift_check methods

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/moodle-tool_objectfs/pull/183
