### ISSUE TITLE
Have a config option to synchronously write files directly into external storage

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#156]
Generally once we have finished the migration of the files from local to external, we could safely swap over to writing directly to the external store. This was always in the original design plan but seems to have been forgotten along the way.

Once we are in this state of most things being external then the cron sync tasks can be run less regularly, eg at night, and only be there to catch anything that slips through or errors for whatever reason.

Tasks:
* [ ] Soft version: when a file is uploaded, synconously create the objectfs metadata for it so it is always 'known' and not dependent on cron to find them. This by itself will reduce some sync latency as it will be at best the second cron task

* [ ] safe version: write to local disc, flag metadata as above, then copy to remote disc and update metadata

* [ ] full direct write to remote, never touch local disc. I suspect in some use cases code immediately after it will then use the file and require it to be local again and pull it back. Maybe things like thumbnails or whatever, need to test and see. Would be good to have some sort of 'churn' metric in place before implementing this

**Comment by samber** [comment]
+1

In a cluster of multiple Moodle instances, a lag in file upload is not very convenient!

**Comment by brendanheywood** [comment]
@samber are you talking about lag syncing the files in the backing store, or front end browser upload lag?

**Comment by samber** [comment]
@brendanheywood I'm talking about lag between upload to moodledata/ and upload to s3.

During 1min (minimal cron job execution interval), the uploaded file is registered in database, but not uploaded to object storage (s3, azure, whatever...).

**Comment by brendanheywood** [comment]
@samber ok sure, but that's an internal detail - I'm curious what the actual inconvenience is for you? It's all abstracted away and under various conditions it needs to later sync back to local disc and then be removed again anyway. So what exactly is the inconvenience, is it just the inconsistency when an sysadmin is looking at the raw mounts or in S3, or something else like marginal billing differences? I can't see any end-user inconvenience they are oblivious.

**Comment by samber** [comment]
Example:

2 Moodle instances A and B, with load balancer in front:

- teacher uploads image (routed to A)
- Moodle redirects to a preview page
- browser requests backend to get image (routed to B) => 404
- teacher saves course
- student go to course and fetch image (routed to B) => 404

- 1 minute later: cron tasks sync image to S3
- 200 everywhere

This is inconsistent and it leads teachers to bug reporting.

**Comment by brendanheywood** [comment]
@samber that feels very wrong, the objectfs should always serve a file either from local shared disk in the $CFG->dataroot or from s3. If there is a 404 there is either a bug here or something weird with your setup, but that is independent of this new feature.

When you say '2 Moodle instances A and B' do you mean two identical front ends connected to the same database? If so then it sounds like your two front ends are not sharing a common dataroot? eg nfs mount. This must be the case or you'll have a bunch of problem, even if this issue was implemented.

**Comment by samber** [comment]
What kind of problems ?

**Comment by brendanheywood** [comment]
Jeez all sorts of bad voodoo. It's best to split the concepts of 'datadir' vs 'filedir'. filedir stores files managed by the file api, like student files. datadir is just raw disk that moodle uses for other stuff, like configuration files. Both are required to be shared. By default filedir is managed by core and is immutable but it lives inside datadir too. Objectfs replaces filedir but doesn't touch the large datadir concept.

Let's assume that objectfs always fully reads and writes to s3, but that not everything which lives in $CFG->dataroot. There are temp dirs, cache dirs, backupdirs all of which much be shared:

https://github.com/moodle/moodle/blob/master/config-dist.php#L435
https://github.com/moodle/moodle/blob/master/config-dist.php#L443

If these are split I'd expect all sorts of failure, some overt like the 404s, some subtle like inconsistent caches, missing temp files which could break backups, analytics, trashdir / recyclebin, potentially anything. A biggy that would worry me is the MUC config file:

https://github.com/moodle/moodle/blob/master/cache/classes/config.php#L125

**Comment by brendanheywood** [comment]
Closing this as dup of #26
