### ISSUE TITLE
Support for Google Cloud Storage?

### ISSUE THREAD

**Issue by sherifkozman** [catalyst/moodle-tool_objectfs#164]
Hello, 

Is there any plans or roadmap for supporting Google Cloud storage as an additiona blob storage source ?

**Comment by brendanheywood** [comment]
@sherifkozman sorry we do not have any particle plans for this, if you would like to sponsor this please contact us:

https://www.catalyst-au.net/content/contact-us

**Comment by jamiechapmanbrn** [comment]
I've added a PR that works with gcs here: https://github.com/catalyst/moodle-tool_objectfs/pull/249/files

**Comment by brendanheywood** [comment]
thanks @jamiechapmanbrn
