### ISSUE TITLE
xsendfile method is dead code

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#166]
It looks very unlikely that this code has ever been tested:

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/object_file_system.php#L381-L398

The remote url that is returned won't mean anything to apache / nginx so this will fail. This should just return false instead

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/moodle-tool_objectfs/pull/183
