### ISSUE TITLE
Config page makes request to digitaloceanspaces.com

### ISSUE THREAD

**Issue by garthwilliamson** [catalyst/moodle-tool_objectfs#172]
When loading the config page with the aws plugin installed, the config page attempts to contact sfo2.digitaloceanspaces.com. With a restrictive firewall, this can result in the config page timing out.
An option would be not to attempt to contact the endpoints unless a test button was pressed.

**Comment by brendanheywood** [comment]
I think this can be closed. We've just redone the config pages so that only 1 of the various stores settings is actually shown, so you choose aws, and you should not see anything related to DO or Azure etc it will land on master shortly
