### ISSUE TITLE
Implement tests for *presigned_url* methods

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_objectfs#176]
https://github.com/catalyst/moodle-tool_objectfs/commit/a3b600eadd07ffe7645385dbbe5d3145cd930a5c

Before this commit will be merged into master branch new methods should be covered by tests:
- [ ] _presigned_url_configured()_
- [ ] _presigned_url_should_redirect()_

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/moodle-tool_objectfs/pull/183
