### ISSUE TITLE
3.71 compatability

### ISSUE THREAD

**Issue by jmayermsi** [catalyst/moodle-tool_objectfs#185]
Just wondering if anyone is working on compatibility for Moodle 3.71. When I try to install I get this message. I am most interested in the S3 portion:

Debug info: Errors found in XMLDB file: PATH attribute does not match file directory: admin/tool/objectfs/db
Error code: ddlxmlfileerror
×Stack trace:
line 352 of /lib/ddl/database_manager.php: ddl_exception thrown
line 368 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
line 606 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
line 1869 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by dmitriim** [comment]
Hi @jmayermsi 
Do you use thelatest code from master branch of this repo?

**Comment by jmayermsi** [comment]
Thank you, I just installed the master branch.  However, I am getting this message when selecting S3:

Client for current file system is not available. Please install the required dependencies if this is the desired object storage client.

**Comment by danmarsden** [comment]
please see the installation instructions in our wiki:
https://github.com/catalyst/moodle-tool_objectfs#installation

You have likely missed something.
