### ISSUE TITLE
Remove presigned URLs settings if core doesn't support it

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_objectfs#187]
We need to hide presigned URL stuff if Moodle doesn't support stuff from https://tracker.moodle.org/browse/MDL-66304

- setting page
- test page
- ignore presigned URLs setting if they were enabled

**Comment by brendanheywood** [comment]
Can we detect this dynamically? It might be easier to just have a help text which says 'if you want this you need to cherry pick X' and also have that in the installation in the readme

**Comment by dmitriim** [comment]
as an option it could check if new methods exist.  But I haven't looked at the code carefully.

**Comment by brendanheywood** [comment]
There is no new method, there is base implementation which we override, but the chunk of core change that we need isn't something that I think we can dynamically inspect (other than opening and parsing that php and looking for some code which is gross).

**Comment by dmitriim** [comment]
isn't supports_xsendfile a new one?

**Comment by brendanheywood** [comment]
Ah yes you are right:

1) if that returns false then we can hide the settings
2) also test if that method exists for backward compat and also hide it is it doesn't exist
3) But even if it is true it may not actually work unless that patch is applied. <-- this is what I meant
