### ISSUE TITLE
Determining if files are being called from remote file system

### ISSUE THREAD

**Issue by jmayermsi** [catalyst/moodle-tool_objectfs#188]
How can I tell if files are being called from the remote file system? Not seeing any network traffic in browser showing that the files are being loaded from S3.

**Comment by brendanheywood** [comment]
From the browsers point of view there is zero difference, this is purely internal to moodle. You can see where the files are by looking at this report:

object_status.php

(Note: what I said above is true now, it will not always be true in future when we implement signed urls which will send traffic directly to s3 if turned on)
