### ISSUE TITLE
If xsendfile via redirects is turned off, then just hard exist fast without any lookups

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#189]
This should work both with and without this patch applied:

https://tracker.moodle.org/browse/MDL-66304

**Comment by golenkovm** [comment]
1. When MDL-66304 is not backported and xsendfile is turned off:
`!empty($CFG->xsendfile)` is `false` here:
https://github.com/moodle/moodle/blob/3eca8fedf045cb8ee6bf45b060a513338b64831b/lib/filelib.php#L2162
, so we don't call `$fs->xsendfile($file->get_contenthash())` and therefore we don't do any lookups.

2. When MDL-66304 is backported (or this is a 3.8-3.9 moodle branch):
We drill down to `presigned_url_should_redirect()` method here:
https://github.com/catalyst/moodle-tool_objectfs/blob/66bcb78794672e6db86b885f46e18caf2b780bbb/classes/local/store/object_file_system.php#L731
and then return `false` on `presigned_url_configured()` check. So no lookup is performed as well.

Closing this off.
