### ISSUE TITLE
Clarification of a setting

### ISSUE THREAD

**Issue by gazlee** [catalyst/moodle-tool_objectfs#190]
Hi, when changing the minimum age and consistency delay settings, is the time specified taken from the date the plugin was enabled or when the files were actually uploaded?

We have a Moodle site with lots of historic content from many years ago and I have set the minimum age to 2 weeks but nothing has been uploaded yet, but the plugin has only been enabled for a couple of days, just wanted to check that this was normal?

Thanks
Gary

**Comment by brendanheywood** [comment]
No its from the file age, so something is clearly not working. I'd run the cron tasks manually and see whats going on.

**Comment by gazlee** [comment]
Hi, when running the cron task manually from the cli I get the following output. Everything seems to complete successfully but no actions are taken?

`Scheduled task complete: Object file system upload task (tool_objectfs\task\push_objects_to_storage)
Execute scheduled task: Object file system delete local objects task (tool_objectfs\task\delete_local_objects)
... started 15:06:14. Current memory use 35.2MB.
No candidate objects found.
... used 1 dbqueries
... used 0.0023219585418701 seconds
Scheduled task complete: Object file system delete local objects task (tool_objectfs\task\delete_local_objects)
Execute scheduled task: Object file system download objects task (tool_objectfs\task\pull_objects_from_storage)
... started 15:06:14. Current memory use 35.2MB.
No candidate objects found.
... used 1 dbqueries
... used 0.0022950172424316 seconds
Scheduled task complete: Object file system download objects task (tool_objectfs\task\pull_objects_from_storage)
Execute scheduled task: Object file system check objects location task (tool_objectfs\task\check_objects_location)
... started 15:06:14. Current memory use 35.2MB.
. Total time taken: 3.0994415283203E-6 seconds. Location change summary:
... used 1 dbqueries
... used 25.673508882523 seconds
Scheduled task complete: Object file system check objects location task (tool_objectfs\task\check_objects_location)
Cron script completed correctly
Cron completed at 15:06:40. Memory used 36.2MB.
Execution took 29.181373 seconds`

**Comment by gazlee** [comment]
edit: I just tried changing "Maximum transfer task runtime" to 5 mins and re-running the cron task it has now uploaded a small amount of files:

Execute scheduled task: Object file system upload task (tool_objectfs\task\push_objects_to_storage)
... started 15:29:38. Current memory use 33.1MB.
copy_object_from_local_to_external. Total time taken: 0.064017057418823 seconds. Location change summary:
local -> duplicated. Objects moved: 13. Total size: 5MB. 
... used 28 dbqueries
... used 1.2183051109314 seconds
Scheduled task complete: Object file system upload task (tool_objectfs\task\push_objects_to_storage)

Could this have been the issue or is it coincidence, I assumed that a setting of '0' would just mean unlimited?

**Comment by gazlee** [comment]
Yep, looks like it was just that, sorry! Lots more data is moving across now.
