### ISSUE TITLE
Question about usage 

### ISSUE THREAD

**Issue by SergioRBJ** [catalyst/moodle-tool_objectfs#199]
I have a question about using this plugin. Can I use it to replace moodledata filedir with s3?

**Comment by brendanheywood** [comment]
Yes, you can see the range of use cases here:

https://github.com/catalyst/moodle-tool_objectfs#use-cases

NOTE: this doesn't completely remove filedir, it is a hybrid filesystem and files will get pushed and pulled to the object store as needed. Certain types of actions inside moodle require a local file.

**Comment by SergioRBJ** [comment]
Does the plugin only work on versions below 3.4? I tried to use on a 3.7 and didn't work

**Comment by brendanheywood** [comment]
@SergioRBJ we are using this in production with hundred of clients across all supported stable versions of moodle, and many older ones too.

Are you using the latest code from this repo? And not from the plugin directory?

**Comment by SergioRBJ** [comment]
Yes, i clone this repo and follow the instructions for install. I open a discuss on moodle forum about this https://moodle.org/mod/forum/discuss.php?d=394175 showing my plugin settings. My settings are right? I expect when a student upload a file in assign, the file appears in s3, or a teacher uploads a file/video into course, do the same thing.

**Comment by brendanheywood** [comment]
Is cron running? Are there any errors in the cron log? The upload is not synchronous, it saves it locally and then cron later moves the files around as needed (which can be in either direction)

**Comment by SergioRBJ** [comment]
It was the cron! thanks for the patience :D

I didn't understand how the object deletion works on external storage... if i delete the Moodle file, how it will delete from external storage?

**Comment by SergioRBJ** [comment]
Forget the last question, i miss this instruction:
```php
$CFG->tool_objectfs_delete_externally = 1;
```
