### ISSUE TITLE
Exception - Class 'tool_task\run_from_cli' not found

### ISSUE THREAD

**Issue by azrek** [catalyst/moodle-tool_objectfs#224]
The renderer.php uses the following to run the status report:
tool_task\run_from_cli::is_runnable();

This functionality didn't come into Moodle until 3.5.
This is failing with Totara 12 (the latest Totara) which is based on Moodle 3.3.

Stack trace:
    line 77 of /admin/tool/objectfs/renderer.php: Error thrown
    line 220 of /admin/tool/objectfs/renderer.php: call to tool_objectfs_renderer->get_generate_status_report_update_stats_link()
    line 41 of /admin/tool/objectfs/object_status.php: call to tool_objectfs_renderer->object_status_page_intro()

**Comment by brendanheywood** [comment]
Fixed in https://github.com/catalyst/moodle-tool_objectfs/pull/225
