### ISSUE TITLE
Relative URLs in the scorm are pointing to S3

### ISSUE THREAD

**Issue by jackson-catalyst** [catalyst/moodle-tool_objectfs#231]
In addition to the reported bug #167, we manually changed the mime-type on S3 launched the scorm and noticed that all relative URLs in the scorm are pointing to S3

Suggested fixes are to not server HTML and other files that could have relative links from S3.

**Comment by brendanheywood** [comment]
Maybe duplicate https://github.com/catalyst/moodle-tool_objectfs/issues/227
