### ISSUE TITLE
avoid an extra file db lookup in core

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#263]
* [x] https://tracker.moodle.org/browse/MDL-68342
* [x] take advantage of the above
* [x] add the backporting details to the readme

It needs to work regardless of wether core has this backport or not

**Comment by golenkovm** [comment]
Implemented and merged into master branch.
However, new php7 syntax breaks legacy moodle version with php5 so #316 was created and readme was updated.
