### ISSUE TITLE
CloudFront: file names are replaced by hash

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_objectfs#272]
Having Pre-signed URLs configured and enabled with CloudFront signing method, files get downloaded with hash as their name, not the original name:

![image](https://user-images.githubusercontent.com/22066290/78877103-abd70c80-7a93-11ea-837f-20e2c9dacd0e.png)

**Comment by tic601** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/52949793/80321937-ec9a8980-87e6-11ea-9088-02f32ba1e5da.png)

**Comment by golenkovm** [comment]
This issue is related to AWS CloudFront configuration.
Distribution behaviour needs to be configured to forward query strings:
![image](https://user-images.githubusercontent.com/22066290/80784841-b59aee00-8bc1-11ea-9c3e-12b5c92868ea.png)
Source: https://forums.aws.amazon.com/thread.jspa?messageID=421768
Closing this off.

**Comment by tic601** [comment]
Hello, I have this problem when changing the option in the cloudfront
![test1](https://user-images.githubusercontent.com/52949793/80850219-6dd78f00-8be0-11ea-9dae-9d29f6c2e5bc.PNG)

![test2](https://user-images.githubusercontent.com/52949793/80850226-74660680-8be0-11ea-9b2d-7122b07e1182.PNG)

![test3](https://user-images.githubusercontent.com/52949793/80850229-77f98d80-8be0-11ea-900c-fb062a4149f0.PNG)

**Comment by golenkovm** [comment]
Hi @tic601,
It should have signature, expires and key-id string if Objectfs was properly configured.
Could you please post the full url you are being redirected to? And also Pre-Signed URLs Settings section from admin page (you can blur secret data).

**Comment by tic601** [comment]
https://d10spgtjzs4t6x.cloudfront.net/37/6a/376a4d08be727ae42a6c70e6fe77b11ba6914317?response-content-disposition=inline%3Bfilename%3D%22PLAN%20DE%20TRABAJO%20ITS.pdf%22&response-content-type=application%2Fpdf&Expires=1588414056&Signature=AdmaP7gwmcfkOm1LdFiFzNHJOGKBjp7BjSEW8oEWJIh~0aSF3YmXRfbZjZyDbKTBL0aUC0a55Qb44t4IXAgnbSbksU7SYAt2vT6SjBxrWr-gPWmyktYqKHnl1efyL7-Vn0VI1zOKrOfdaI6RJQYUm4LJ1MtIeWJhMtGY~qns22KdB3D8RcixqOIXl-TmNlMFmNirw7OL-95U0VuANkxJEihVKq7BG6D6kF9853lFyam3baFJqs0yK79I5qxE3kJ7D5Yf-M~uNvoxOpKv0C2b4qWigIRAeZQnWcV-HkYh9PtbZJZ532M58EFHiszthd47uSFG-0PVoZ2K0kGY7cD-HQ__&Key-Pair-Id=APKAJNS7IRRF6YOOPSQQ


![image](https://user-images.githubusercontent.com/52949793/80854824-cfa7f100-8c00-11ea-9807-7e076d41c177.png)

![image](https://user-images.githubusercontent.com/52949793/80854847-f108dd00-8c00-11ea-8a55-7a71d7f049c2.png)

**Comment by golenkovm** [comment]
Hey @tic601 
I've created #302 for this.
Please, let me know if you find a solution.
