### ISSUE TITLE
Test fail - install.xml version

### ISSUE THREAD

**Issue by guillogo** [catalyst/moodle-tool_objectfs#278]
Hi, we are having this error running unit test and using the following environment:

1. PHP 7.0 in Totara 10
2. Merge pull request #269 from catalyst/fix-invalid-property-name

Test:

```
1) tool_xmldb_instal_xml_testcase::test_all_install_xml_files_formatted_correctly
XMLDB file '/siteroot/admin/tool/objectfs/db/install.xml' is different to the generated version, please edit the file in XMLDB editor and save it.
Failed asserting that false is true.

/siteroot/admin/tool/xmldb/tests/install_xml_test.php:52
/siteroot/lib/phpunit/classes/base_testcase.php:600
/siteroot/lib/phpunit/classes/advanced_testcase.php:68

To re-run:
 vendor/bin/phpunit tool_xmldb_instal_xml_testcase admin/tool/xmldb/tests/install_xml_test.php
```

**Comment by Peterburnett** [comment]
This should be fixable by editing and saving the file with no changes in the XMLDB editor, then committing that up. Are you able to make a PR for this @guillogo ? @brendanheywood This may be something we should add to the list of things we want for Moodle-plugin-ci, probably in the check_database_schema check, seems useful, and couldve been caught prior to this

**Comment by guillogo** [comment]
Thank you @Peterburnett I will do it and make a PR. Thanks.

**Comment by kristian-94** [comment]
Merged, closing this issue now, thank you @guillogo !
