### ISSUE TITLE
Local files are not being deleted 

### ISSUE THREAD

**Issue by guillefd** [catalyst/moodle-tool_objectfs#281]
Hi,
local files are not being deleted. 
`Delete local objects` is checked and `min age`  and `consistency delay` are set to minimum.
Files are being copied correctly to S3.
Task is running every 2 minutes with cron, and no error is logged.
Moodle version: Moodle 3.8.2+ (Build: 20200417) / PHP 7.3

What am I missing?

thanks!

**SETUP**
![setup](https://i.gyazo.com/f20c856ad96c44985cec00cacc82fd95.png)

**TASK LOG**
![logs](https://i.gyazo.com/9464036bcda66787bfbeb024f5693f24.png)

**Comment by guillefd** [comment]
So, files are being copied to S3, sync is working fine.
Problem is, after setting up `delete local objects`, the local files are not deleted.
Log is not throwing errors and also not listing the files to be deleted.
what else can I look to fix this?

**Comment by brendanheywood** [comment]
Hmm that all seems right. If it was an s3 permissions issue it would say as much. Did you get anywhere?

**Comment by iBinJubair** [comment]
**1) Check your web server configurations (Apache, Nginx ...)**
What is the `user` and `group` used to run the web server? is it `www-data`, `apache`, `username` ...etc 


**2) Check these settings in your `config.php`**
```php
// They must start with `0` and see the notes below
$CFG->directorypermissions = 0755
$CFG->filepermissions = 0644
```
Note: Make sure that you use [the right permissions](https://docs.moodle.org/39/en/Security_recommendations#Most_secure.2Fparanoid_file_permissions) 


**3) Fix directory and file permissions** 
Run these commands to fix directory and file permissions depending on step 2 and your Moodle installation path
```bash
# for directories
find /var/www/html/ -type d -exec chmod 755 {} +
find /var/www/moodledata/ -type d -exec chmod 755 {} +
# for files
find /var/www/html/ -type f -exec chmod 644 {} +
find /var/www/moodledata/ -type f -exec chmod 644 {} +
```
Note: If you get an error, run the command again and again ...


**4) Fix the owner of directories and files** 
Run these commands to fix directory and file owner depending `user:group` on step 1 and your Moodle installation path
```bash
chown -R www-data:www-data /var/www/html/
chown -R www-data:www-data /var/www/moodledata/
```


**5) What is the user that is used to run Moodle cron job?**
Make sure that you specify the same user used for your web server `e.g www-data` when you run the Moodle cron jobs  `admin/cli/cron.php` using `Crontab` or any other solution.

**Comment by guillefd** [comment]
Hi! thank you for taking the time to answer.
I finally deleted this installation and tried a new one where it all worked with no issues.
(anyway I believe the issue must have been related to some permission setup)
Thanks!
