### ISSUE TITLE
Allow direct uploads to S3

### ISSUE THREAD

**Issue by jgupta** [catalyst/moodle-tool_objectfs#296]
Users should be able to directly update to S3 without files first coming to Moodle.

**Comment by dmitriim** [comment]
@jgupta what is your use case for this?

**Comment by jgupta** [comment]
@dmitriim students uploading a lot of assignments at high concurrency. We have a university who is conducting exams this way.

We want to keep the server's network capacity available for other stuff.

**Comment by dmitriim** [comment]
Ah I got what you mean. 
Are you talking about uploading files "as we go" directly to s3 and not actually saving them to moodle file dir first and then transfer by cron task?

**Comment by dmitriim** [comment]
We have already similar issue https://github.com/catalyst/moodle-tool_objectfs/issues/26
I'll close this one off. 
Not sure if that work is in the current road map, but if you'd like to work on this feature please don't hesitate to submit a pull or if you can sponsor it, please contact us on https://www.catalyst-au.net/contact-us to discuss details.
