### ISSUE TITLE
Investigate stream to tmp file potential issue for files over 2meg

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#335]
There is an issue with s3 streams from the AWS api not being fully seekable, so internally php transparently downloads the entire stream to a tmp file in order to seek over it.

`Read only streams are truly streaming by default and will not allow you to seek. This is because data read from the stream is not kept in memory or on the local filesystem. You can force a "r" stream to be seekable by setting the "seekable" stream context option true. This will allow true streaming of data from Amazon S3, but will maintain a buffer of previously read bytes in a 'php://temp' stream to allow seeking to previously read bytes from the stream.`

https://github.com/catalyst/moodle-local_aws/blob/master/sdk/Aws/S3/StreamWrapper.php#L19-L25

`php://temp will use a temporary file once the amount of data stored hits a predefined limit (the default is 2 MB). The location of this temporary file is determined in the same way as the sys_get_temp_dir() function.`

https://www.php.net/manual/en/wrappers.php.php

These are not visible from inside php and probably live somewhere like:

/tmp/systemd-private-d13ee8ffdaf84a039646d023fd03d636-apache2.service-NkD8xt/tmp/

This means every range request for a large file ends up copying the entire file multiple times over to get the full file served

A rough but working code snippet:

https://gist.github.com/durzo/029ba48d7bf25a920c3a227c70d7d131

**Comment by golenkovm** [comment]
Implemented in #340
