### ISSUE TITLE
Settings page will load forever if using S3 is selected without credentials

### ISSUE THREAD

**Issue by Peterburnett** [catalyst/moodle-tool_objectfs#349]
https://github.com/catalyst/moodle-tool_objectfs/blob/master/settings.php#L142

This check will load files and attempt to do presigned urls test. This needs to be locked behind a connection test, otherwise this will load forever, which has the side effect of stopping you from setting the credentials through the frontend after selected s3

**Comment by dmitriim** [comment]
Also I'm getting following debugging message when objecfs is not configure and debugging on 

Test range request to URL https://17/73/17735b4721faa7d59e1fd8a2300135a3f04c9ea6?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=%2F20200630%2Fap-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200630T120822Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Signature=0ec59636f77cd393b1cbb565b94ac8b7624f2cb175acbd5605ea923c8d0e43bd failed with HTTP code: . Details:
line 727 of /admin/tool/objectfs/classes/local/store/s3/client.php: call to debugging()
line 142 of /admin/tool/objectfs/settings.php: call to tool_objectfs\local\store\s3\client->test_range_request()
line 81 of /lib/classes/plugininfo/tool.php: call to include()
line 625 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
line 8376 of /lib/adminlib.php: call to require()
line 26 of /admin/search.php: call to admin_get_root()
Skip to main content

**Comment by dmitriim** [comment]
And upgrade script gives me 

== Setting new default values ==
ERROR: copy /var/lib/sitedata/moodle37/filedir/b5/f1/b5f150e80dd7f1d534f6da6d5c28d83ba665ac19 to s3:///b5/f1/b5f150e80dd7f1d534f6da6d5c28d83ba665ac19: Error executing "PutObject" on "https://b5/f1/b5f150e80dd7f1d534f6da6d5c28d83ba665ac19"; AWS HTTP error: cURL error 6: Could not resolve host: b5 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/ce/c8/cec8ad914b1e9db83626b98e8d98512616975fdf to s3:///ce/c8/cec8ad914b1e9db83626b98e8d98512616975fdf: Error executing "PutObject" on "https://ce/c8/cec8ad914b1e9db83626b98e8d98512616975fdf"; AWS HTTP error: cURL error 6: Could not resolve host: ce (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/33/aa/33aaf7a69e50c9c0ebb855013ff91a21dda5a536 to s3:///33/aa/33aaf7a69e50c9c0ebb855013ff91a21dda5a536: Error executing "PutObject" on "https://33/aa/33aaf7a69e50c9c0ebb855013ff91a21dda5a536"; AWS HTTP error: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/1b/50/1b50526cc09ba31ecc55b9f6ee63a063a6237912 to s3:///1b/50/1b50526cc09ba31ecc55b9f6ee63a063a6237912: Error executing "PutObject" on "https://1b/50/1b50526cc09ba31ecc55b9f6ee63a063a6237912"; AWS HTTP error: cURL error 6: Could not resolve host: 1b (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/8b/60/8b606bb3b05ec627e2fa5fee28b0ef4591d059fa to s3:///8b/60/8b606bb3b05ec627e2fa5fee28b0ef4591d059fa: Error executing "PutObject" on "https://8b/60/8b606bb3b05ec627e2fa5fee28b0ef4591d059fa"; AWS HTTP error: cURL error 6: Could not resolve host: 8b (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/cb/ea/cbea071b8dce97d672f9ee679923008b37ac932a to s3:///cb/ea/cbea071b8dce97d672f9ee679923008b37ac932a: Error executing "PutObject" on "https://cb/ea/cbea071b8dce97d672f9ee679923008b37ac932a"; AWS HTTP error: cURL error 6: Could not resolve host: cb (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/c0/01/c00148f586db109ffaca3724102e69e2e7996bf0 to s3:///c0/01/c00148f586db109ffaca3724102e69e2e7996bf0: Error executing "PutObject" on "https://c0/01/c00148f586db109ffaca3724102e69e2e7996bf0"; AWS HTTP error: cURL error 6: Could not resolve host: c0 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/17/73/17735b4721faa7d59e1fd8a2300135a3f04c9ea6 to s3:///17/73/17735b4721faa7d59e1fd8a2300135a3f04c9ea6: Error executing "PutObject" on "https://17/73/17735b4721faa7d59e1fd8a2300135a3f04c9ea6"; AWS HTTP error: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
ERROR: copy /var/lib/sitedata/moodle37/filedir/29/8e/298e48df7471b52102869983cc520a39d5e6c22c to s3:///29/8e/298e48df7471b52102869983cc520a39d5e6c22c: Error executing "PutObject" on "https://29/8e/298e48df7471b52102869983cc520a39d5e6c22c"; AWS HTTP error: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
++ Test range request to URL https://17/73/17735b4721faa7d59e1fd8a2300135a3f04c9ea6?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=%2F20200630%2Fap-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200630T121829Z&X-Amz-SignedHeaders=host&X-Amz-Expires=59&X-Amz-Signature=bcd2ee02f69f1408c6b3e67fa528e94b82928636a22047e78c0a4b072f7f2a50 failed with HTTP code: . Details:  ++
* line 727 of /admin/tool/objectfs/classes/local/store/s3/client.php: call to debugging()
* line 142 of /admin/tool/objectfs/settings.php: call to tool_objectfs\local\store\s3\client->test_range_request()
* line 81 of /lib/classes/plugininfo/tool.php: call to include()
* line 625 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
* line 8376 of /lib/adminlib.php: call to require()
* line 8402 of /lib/adminlib.php: call to admin_get_root()
* line 200 of /admin/cli/upgrade.php: call to admin_apply_default_settings()

**Comment by Peterburnett** [comment]
Ah thanks @dmitriim I missed the debugging output. I will fix this PR when I can

**Comment by vlasov01** [comment]
I've clone the master, installed plugin and I've got this issue again - settings page loads forever. 
Where I can set S3 credentials?
