### ISSUE TITLE
delete_local_objects task failing on 3.9 site using SWIFT

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_objectfs#382]
Scheduled task failed: Object file system delete local objects task (tool_objectfs\task\delete_local_objects),Coding error detected, it must be fixed by a programmer: A lock was created but not released at:

/admin/tool/objectfs/classes/local/store/object_file_system.php on line 235

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory->get_lock(113294202);
 $lock->release();  // Locks must ALWAYS be released like this.

Backtrace:
* line 108 of /admin/tool/objectfs/classes/local/object_manipulator/manipulator.php: call to core\lock\lock->__destruct()
* line 81 of /admin/tool/objectfs/classes/local/object_manipulator/manipulator_builder.php: call to tool_objectfs\local\object_manipulator\manipulator->execute()
* line 66 of /admin/tool/objectfs/classes/task/task.php: call to tool_objectfs\local\object_manipulator\manipulator_builder->execute()
* line 248 of /lib/cronlib.php: call to tool_objectfs\task\task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 79 of /admin/cli/cron.php: call to cron_run()

**Comment by danmarsden** [comment]
seems to be coming from: 
https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/local/store/swift/client.php#L131

**Comment by danmarsden** [comment]
more specifically the obj->retrieve call.

looks like there's a newer version of the openstack libs that I'm using - might see if that helps but might have to wait for a couple of weeks.
https://github.com/php-opencloud/openstack/commits/master

**Comment by danmarsden** [comment]
This seems to prevent the fatal from occurring.
```
--- a/admin/tool/objectfs/classes/local/store/swift/client.php
+++ b/admin/tool/objectfs/classes/local/store/swift/client.php
@@ -137,7 +137,7 @@ class client extends object_client_base {
 
             $obj->retrieve();
 
-        } catch (BadResponseError $e) {
+        } catch (\OpenStack\Common\Error\BadResponseError $e) {
```
Looks like a few other places where "BadResponseError" is used without the full path - we might need to review those at some point.

**Comment by degodfather** [comment]
@danmarsden off topic, so 3.9 is supported?

**Comment by brendanheywood** [comment]
Yes we are using this in 3.9
