### ISSUE TITLE
Will this work with Scorm files?

### ISSUE THREAD

**Issue by jmsobe** [catalyst/moodle-tool_objectfs#383]
Are SCORM files supported by the plugin? The intent of course is to have one repository for SCORM files uploaded via the interface to S3.

**Comment by brendanheywood** [comment]
Higher levels in Moodle are not aware of where the filesystem stores things, so yes this works with scorm, at least with the mod_scorm activity. It sounds like you want to manually upload files to s3 which is not how this works at all, neither admins not end users will never interact with s3
