### ISSUE TITLE
Help wanted. Can't make Pre-signed URLs work

### ISSUE THREAD

**Issue by jesusvila** [catalyst/moodle-tool_objectfs#387]
Hi i've installed last Moodle 3.8 from git. Installed aws and moodle-tool-objetctfs repos and patched files

```
cd /var/www/html
git clone git://git.moodle.org/moodle.git
cd moodle
git branch -a
git branch --track MOODLE_38_STABLE origin/MOODLE_38_STABLE
git checkout MOODLE_38_STABLE
(installed database, create user, ...)
git clone https://github.com/catalyst/moodle-local_aws.git /var/www/html/moodle/local/aws
git clone https://github.com/catalyst/moodle-tool_objectfs.git /var/www/html/moodle/admin/tool/objectfs
cd /var/www/html/moodle
git am --whitespace=nowarn < admin/tool/objectfs/patch/core38.diff
sudo -u www-data /usr/bin/php /var/www/html/moodle/admin/cli/upgrade.php --non-interactive
```

and added to config.php

```
$CFG->alternative_file_system_class = '\tool_objectfs\s3_file_system';
or
$CFG->alternative_file_system_class = '\tool_objectfs\digitalocean_file_system';
```

I've tried with S3 and with Digital Ocean Spaces. Added credentials and configure the objectfs plugin.

```
version -> 2020062400
enabletasks -> 1
maxtaskruntime -> 3600
enablelogging -> 0
useproxy -> 0
sizethreshold -> 10240
batchsize -> 10000
minimumage -> 600
deletelocal -> 0
consistencydelay -> 600
filesystem -> \tool_objectfs\s3_file_system
preferexternal -> 0
lastcron -> 1606594022
s3_usesdkcreds -> 0
s3_key -> xxx
s3_secret -> xxx
s3_bucket -> xxx
s3_region -> eu-west-2
s3_base_url -> 
proxyrangerequests -> 1
enablepresignedurls -> 1
expirationtime -> 7200
presignedminfilesize -> 0
signingwhitelist -> *
signingmethod -> s3
```

File upload works correctly.

I've done a Pre-Signed URL Testing and it shows green icons but it wrote

1) Test links below to download file with contenthash as its name:
Download file: testimage.png
Redirecting to external storage: https://--mymoodle-url--/moodle/pluginfile.php/1/tool_objectfs/settings/0/testimage.png?forcedownload=1

and the other links are equal. All files are downloaded correctly, but from my moodle url, not directly from (S3 | Digital Ocean)

I've tried apache and nginx.  Also i've tried installed and configured x-sendfile without success.

I'm missing something??

**Comment by mjthompson** [comment]
G'day

My suspicion is that you haven't whitelisted any file types in Pre-Signed URLs Settings > Pre-Signed URL whitelist.

Cheers,
Matt

**Comment by mjthompson** [comment]
Edit: Deleted my suggestion - Seems I didn't read the post fully :)

**Comment by jesusvila** [comment]
Pre Signed urls work today. Same configuration as last day. 

Same moodle version (3.8.6+), clean database, empty S3 bucket, same files on course.

**Comment by jianwei0510** [comment]
May I know how do you fix in the end? I encountered same problem and can't make Moodle serve files from s3 with presigned url
