### ISSUE TITLE
Rework tool_sssfs into tool_objectfs

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#40]
95% of the logic in the plugin can be applied to any object storage that provides a stream wrapper that can be used with it. The code should be abstracted in such a way that adding a new type of object storage is as easy as possible.

The majority of the work will be done in adding a new objectspecific_client.php

**Comment by kenneth-hendricks** [comment]
Steps in my mind that will allow this to happen.

1. Complete rename of plugin and methods
2. restructuring of code e.g. client folder to hold different clients
3. Create a base client class that can be extended.
4. make sure the file_system and all code outside the s3 client has no s3 specific logic.
5. Think about adding a client CFG variable
6. Make settings page extendable.

**Comment by brendanheywood** [comment]
not needed at all
