### ISSUE TITLE
Moodle Files Deletion 

### ISSUE THREAD

**Issue by akahky** [catalyst/moodle-tool_objectfs#404]
Hello All, 
     I have two nodes where Moodle is running, and objectfs is installed and running on both nodes and it is configured to move all files larger than 10K to a shared storage and the consistency delay is 10 minutes and delete local objects is enabled.
I am facing a strange issue that files are not deleted although their sizes are around 300MB from one of the nodes.

Would you please advise how to solve such issue?

**Comment by guillefd** [comment]
Have you added this on config.php?

_If you intend to allow deletion of remote files then add the following line._
`$CFG->tool_objectfs_delete_externally = 1;`

**Comment by akahky** [comment]
Thanks a loft for the reply. 
No, I am not intending to delete the remote files, I mean the local files uploaded to moodeldata folder are not delete after uploaded to the shared storage.

**Comment by brendanheywood** [comment]
> objectfs is installed and running on both nodes

What exactly does this mean?

When you run the cron tasks manually what do they say they have done? And what does the object status report say where all the files are?

Also for various reasons what you see could be normal, ie if that file is used by moodle and is required to be local then it will get pulled back down

**Comment by akahky** [comment]
let me clarify this point, may be I miss explained that, I have two Moodle nodes connected to the same database and a load balancer in front of these two nodes.

When the user uploads a file to Moodle, it is uploaded to the local directory on the node then objectfs synchronizes the data with a separate shared directory and deletes the file uploaded on this node so that the files can be accessible from both nodes and in the configuration file we set $CFG->alternative_file_system_class  to point to the shared directory so the files can be served from this shared directory.

The issue I am facing is that some files are not removed from the not removed from the node it is uploaded to and so the disk space usage on the nodes differ, one of these nodes has over 60 GB files stored on it.

Would you please let me know how to avoid having the files cashed on one node?

**Comment by brendanheywood** [comment]
It sounds like your moodle simply is not setup correctly. The $CFG->dataroot for moodle MUST be shared across all nodes via nfs / gluster / etc and this has nothing to do with objectfs. Moodle will break is a myriad of ways if that is not the case.

> $CFG->alternative_file_system_class to point to the shared directory so the files can be served from this shared directory.

This doesn't sound right either, that config points to a php class, not a directory. This should be set to a store implementation, such as AWS s3, and then you need to create that in AWS and configure it in Moodle.

**Comment by brendanheywood** [comment]
For more info see

https://docs.moodle.org/310/en/Server_cluster#.24CFG-.3Edataroot
