### ISSUE TITLE
master/MOODLE_310_STABLE branch divergence

### ISSUE THREAD

**Issue by marxjohnson** [catalyst/moodle-tool_objectfs#409]
Hi,
We've just merged Moodle 3.10, and I was looking at switching to the MOODLE_310_STABLE branch of objectfs as it contains updates to the unit test signatures that are needed (8f32ae5f9fffd1c6b4053b6072d0b18f3dfb2d1d).
However, I noticed that a commit we need on master (6d28a08b26cc233f489fd4b85e49a3e48c66785b) has not been ported to the 310 branch. This means there is no branch that we can use with 3.10.

Given that the unit test fixes will be needed for future versions of Moodle too, it seems like these should be on master as well. Can this be reconciled?

**Comment by brendanheywood** [comment]
To be honest I'm not quite sure what the MOODLE_310_STABLE is, I don't think it should exist. Our entire fleet is all on master except for really old stuff on 27-32-STABLE. The officially supported branches are:

https://github.com/catalyst/moodle-tool_objectfs#branches

For backporting the things needed for it to work to it's best see:

https://github.com/catalyst/moodle-tool_objectfs#applying-core-patches

**Comment by brendanheywood** [comment]
Ok got some more info, this branch was a work in progress but not finished. We will likely blow it away and / or bring it up to speed and then update the readme, we'll keep all the comms in this issue

**Comment by brendanheywood** [comment]
Also worth noting that we don't have any clients on 3.10 yet, and it's not clear if we will have any on 3.11 - so the internal priority for this is not pressing. It's in our queue but if you or anyone want to get a start on it that is always welcome.

**Comment by danmarsden** [comment]
this was fixed a while back.
