### ISSUE TITLE
Moodle 3.10 - ObjectFS 

### ISSUE THREAD

**Issue by akahky** [catalyst/moodle-tool_objectfs#421]
Hello All,
I am currently running moodle 3.10 and objectfs to upload the files to DigitalOcean space, the issue is that the files are not being synchronized with DigitalOcean space.

I have a couple of questions:

in digitalocean space settings should the space name be written fully qualified such as "space.fra1.digitaloceanspaces.com" or just "space" and set the region to fr1?
is there anyway to run objectfs manually to force files synchronization?
is cron job required to synchronize the data? if yes, how can I do that?
Where can I find the logs of objectfs?
Appreciating your feedback.

**Comment by guillefd** [comment]
I'm using objectfs wth moodle 3.9 and Digitalocean, working good so far

- digitalocean space settings space name: 
just the "space name", not the full url

- run objectfs manually to force files synchronization:
go to admin > server > scheduled tasks  
MOODLE_URL/admin/tool/task/scheduledtasks.php  
search for "Object file system upload task", click on "run now"   (or run on moodle CLI)

-is cron job required to synchronize the data
yes, just setup standard moodle cron

-Where can I find the logs of objectfs?
go to MOODLE_URL/admin/tasklogs.php
filter by "objectfs"

**Comment by akahky** [comment]
Thanks a lot, I have the following tasks defined already and they are running successfully yet files are not being synchronized.
Object file system check objects location task
Object file system delete local empty directories task
Object file system delete local objects task
Object status report generator task
Object file system download objects task

Do I still need to have a cron job even if these tasks already defined?

**Comment by akahky** [comment]
one more issue, DigitalOcean Space has about 1800 files before the upgrade, all the files added after the upgrade are not synchronized to DigitalOcean space and there is no errors in the logs, how can I resynchronize and upload the missing files to Space?

**Comment by guillefd** [comment]
have you checked this? https://github.com/catalyst/moodle-tool_objectfs/pull/413
the master branch does not include this fix yet, apply mannualy and it should work

**Comment by akahky** [comment]
Thanks, this fixed the issue.
