### ISSUE TITLE
deleted file don't remove from remote!

### ISSUE THREAD

**Issue by hsaeedian** [catalyst/moodle-tool_objectfs#427]
hi
When I delete a file, that file is moved to the Trash directory in moodledata,  and after synced the file, in S3 both files remain and the deleted file still remain. Although I have enabled file deletion in the moodle config.php !
how can i see the logs to find the problem

**Comment by brendanheywood** [comment]
@hsaeedian this required a setting to be put into config.php, we have just pushed an improvement which exposes this setting in the admin settings UI. Please take a look at that setting, code is here:

https://github.com/catalyst/moodle-tool_objectfs/pull/429
