### ISSUE TITLE
Feedback , round 2 for FSAPI patch

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#43]

**Comment by kenneth-hendricks** [comment]
/**
     * Determine whether the file is present on the local file system somewhere.
     *
     * @param stored_file $file The file to ensure is available.
     * @return bool
     */
    public function is_file_readable_remotely_by_storedfile(stored_file $file) {
        if (!$file->get_filesize()) {
            // Files with empty size are either directories or empty.
            // We handle these virtually.
            return true;
        }

        $path = $this->get_remote_path_from_storedfile($file, false);
        if (is_readable($path)) {
            return true;
        }

        return false;
    }


$path = $this->get_remote_path_from_storedfile($file, false);
but 
protected function get_remote_path_from_storedfile(stored_file $file) {

**Comment by kenneth-hendricks** [comment]
* A local copy of the file _will_ be fetched if $fetchifnotfound is tree.

**Comment by kenneth-hendricks** [comment]
inconsistancies in style

        if (is_readable($path)) {
            return true;
        }

        return false;


vs 

        return is_readable($path);

**Comment by kenneth-hendricks** [comment]
Think there's a bug:

1) tool_objectfs\tests\pusher_testcase::test_pusher_can_push_multiple_objects
Error: Call to undefined method dml_write_exception::get_message()

/var/www/siteroot/lib/filestorage/file_storage.php:1624
/var/www/siteroot/admin/tool/objectfs/tests/tool_objectfs_testcase.php:78
/var/www/siteroot/admin/tool/objectfs/tests/tool_objectfs_testcase.php:125
/var/www/siteroot/admin/tool/objectfs/tests/pusher_test.php:106
/var/www/siteroot/lib/phpunit/classes/advanced_testcase.php:80

**Comment by brendanheywood** [comment]
Can we close this off now?
