### ISSUE TITLE
Is there a way to ensure all remote files are moved back locally?

### ISSUE THREAD

**Issue by mchurchward** [catalyst/moodle-tool_objectfs#434]
I have been using this plugin with the local files being removed when they are moved remotely. Now I would like to uninstall the plugin, and go back to a local file system. How can I make sure that all remote files are moved back to the local storage?

**Comment by guillefd** [comment]
Yes, on Object Status report: MOODLE_URL/admin/tool/objectfs/object_status.php
check field "Only in external storage" is 0

My approach is:
-change "min size threshold" to extreme high (ie: 1gb) and wait all files are downloaded again to local disk.

**Comment by mchurchward** [comment]
Hmmm... That didn't seem to work for me. I have the same number of objects showing as "Only in external storage".

This is what I have for settings:

Minimum size threshold (bytes): 10737418240
Minimum age: 1 minutes
Delete local objects: no
Consistency delay: 5 minutes

**Comment by guillefd** [comment]
With that settings it should work.
Is cron running? 
also I would check if the "objectfs_" scheduled are running correctly and have no errors.

**Comment by mchurchward** [comment]
Okay. After a few more cron runs, things seem to have fixed themselves. "Only in external storage" now shows zero.

Thanks!

**Comment by danmarsden** [comment]
cool! - transfer to object storage and then transfer back can require a number of cron cycles - there's a bit of code in there that tries to prevent it hitting API's too hard.
