### ISSUE TITLE
PHP Undefined property notice

### ISSUE THREAD

**Issue by mchurchward** [catalyst/moodle-tool_objectfs#435]
When creating my test environment (php admin/tool/phpunit/cli/init.php), the following notice was displayed:

PHP Notice:  Undefined property: stdClass::$deleteexternal in /moodle/admin/tool/objectfs/classes/local/store/object_file_system.php on line 66

Notice: Undefined property: stdClass::$deleteexternal in /moodle/admin/tool/objectfs/classes/local/store/object_file_system.php on line 66

**Comment by danmarsden** [comment]
weird - thanks for the report - probably related to some code I added recently... PR's welcome ;-)

**Comment by danmarsden** [comment]
should be fixed in latest branch now.
