### ISSUE TITLE
Moodle 4.0 changes to display_size trigger unit test failures in tool_objectfs

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_objectfs#436]
MDL-72643 landed this week which tidies up Moodle's display_size function, but objectfs expects the "old" format and so reports failures:

1) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #2 (0, 100, 'size', 0, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:0%">0 bytes</div>'
+'<div class="ofs-bar" style="width:0%">0 bytes</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

2) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #3 (0, 100, 'runningsize', 0, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:0%">0% (0 bytes)</div>'
+'<div class="ofs-bar" style="width:0%">0% (0 bytes)</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

3) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #5 (0, 100, 'size', 2, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:0%">0 bytes</div>'
+'<div class="ofs-bar" style="width:0%">0 bytes</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

4) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #6 (0, 100, 'runningsize', 2, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:0%">0.00% (0 bytes)</div>'
+'<div class="ofs-bar" style="width:0%">0.00% (0 bytes)</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

5) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #8 (10, 100, 'size', 2, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:10%">10 bytes</div>'
+'<div class="ofs-bar" style="width:10%">10 bytes</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

6) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #9 (10, 100, 'runningsize', 2, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:10%">10.00% (10 bytes)</div>'
+'<div class="ofs-bar" style="width:10%">10.00% (10 bytes)</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

7) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #11 (12345678, 123456789, 'size', 0, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:10%">11.8MB</div>'
+'<div class="ofs-bar" style="width:10%">11.8 MB</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

8) tool_objectfs\tests\object_status_testcase::test_object_status_add_barchart_method with data set #12 (12345678, 123456789, 'runningsize', 2, '<div class="ofs-bar" style="w...</div>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div class="ofs-bar" style="width:10%">10.00% (11.8MB)</div>'
+'<div class="ofs-bar" style="width:10%">10.00% (11.8 MB)</div>'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:208
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

9) tool_objectfs\tests\object_status_testcase::test_object_status_get_size_range_from_logsize with data set #1 ('10', '1KB - 2KB')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1KB - 2KB'
+'1.0 KB - 2.0 KB'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:239
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

10) tool_objectfs\tests\object_status_testcase::test_object_status_get_size_range_from_logsize with data set #2 ('11', '2KB - 4KB')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2KB - 4KB'
+'2.0 KB - 4.0 KB'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:239
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

11) tool_objectfs\tests\object_status_testcase::test_object_status_get_size_range_from_logsize with data set #3 ('20', '1MB - 2MB')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1MB - 2MB'
+'1.0 MB - 2.0 MB'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:239
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

12) tool_objectfs\tests\object_status_testcase::test_object_status_get_size_range_from_logsize with data set #4 ('21', '2MB - 4MB')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2MB - 4MB'
+'2.0 MB - 4.0 MB'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:239
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

13) tool_objectfs\tests\object_status_testcase::test_object_status_get_size_range_from_logsize with data set #5 ('30', '1GB - 2GB')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1GB - 2GB'
+'1.0 GB - 2.0 GB'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:239
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

14) tool_objectfs\tests\object_status_testcase::test_object_status_get_size_range_from_logsize with data set #6 ('31', '2GB - 4GB')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2GB - 4GB'
+'2.0 GB - 4.0 GB'

/var/www/html/admin/tool/objectfs/tests/object_status_test.php:239
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by TomoTsuyuki** [comment]
It's fixed in #466
