### ISSUE TITLE
Add cli utility - objectcheck

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#44]
There should be a utility cli script to check every filehash and it's location, correcting them as it can.

**Comment by brendanheywood** [comment]
Some thoughts re monitoring on top of this:

* [ ] this could possibly also be a background task which periodically cycles through everything and checks
* [ ] if a file is missing it needs to store this failure state in the sync table
* [ ] write a highly optimized yes / no query that we can ping with nagios / icinga so say if there are any missing files
* [ ] if a file is attempted to be served and can't be found then auto fix up it's state

**Comment by brendanheywood** [comment]
* [ ] need to think about how this can stay working when the rate of file additions is fast enough that this may never complete with a large enough data set. eg possibly leverage ad hoc tasks so we can queue up work in parallel

**Comment by kenneth-hendricks** [comment]
Closing, functionality covered by error state
