### ISSUE TITLE
new moodle coding guildeline rule triggering errors

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_objectfs#460]
https://github.com/moodlehq/moodle-local_codechecker/pull/169

Unexpected MOODLE_INTERNAL check. No side effects or multiple artifacts detected.

**Comment by keevan** [comment]
https://github.com/moodlehq/moodle-local_codechecker/pull/174

This has changed to a warning now, so it should no longer be triggering errors. That said, still good to clean up.
