### ISSUE TITLE
I have tried to upload file on s3 But it is not uploaded.

### ISSUE THREAD

**Issue by alankaredu** [catalyst/moodle-tool_objectfs#464]

**Comment by danmarsden** [comment]
Please send us your credit card details.... no... seriously, the best place to ask for free help with Moodle is in the community forums on moodle.org -(make sure when you create a new forum post you provide a lot more information on what you have tried etc...)

If you are looking for commercial level support use the contact links in the readme to reach out and we can provide information on our support rates.
