### ISSUE TITLE
If a file isn't in local or remote then flip the bit so we can warn in icinga

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_objectfs#47]

**Comment by kenneth-hendricks** [comment]
By focusing on
- get_actual_object_location_by_hash which is called by the pullback methods
- the file moving functions - delete_object_from_local_by_hash, copy_object_from_local_to_remote_by_hash, copy_object_from_remote_to_local_by_hash
-the non pull back methods: readfile, xsendfile, get_content, get_content_file_handle

we will hit full coverage for this.
