### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Objectfs does not implement a trashdir.

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_objectfs#471]
On a freshly upgraded from 3.5 to 3.9 instance (site-data is potentially missing). Object fs is set as a file system, but not configured. 

```
Coding error detected, it must be fixed by a programmer: Objectfs does not implement a trashdir.

More information about this error

×Debug info:
Error code: codingerror
×Stack trace:
line 1022 of /admin/tool/objectfs/classes/local/store/object_file_system.php: coding_exception thrown
line 253 of /lib/filestorage/file_system_filedir.php: call to tool_objectfs\local\store\object_file_system->get_trash_fullpath_from_hash()
line 596 of /admin/tool/objectfs/classes/local/store/object_file_system.php: call to file_system_filedir->recover_file()
line 127 of /lib/filestorage/file_system_filedir.php: call to tool_objectfs\local\store\object_file_system->recover_file()
line 384 of /lib/filestorage/file_system.php: call to file_system_filedir->get_local_path_from_storedfile()
line 583 of /lib/filestorage/stored_file.php: call to file_system->get_imageinfo()
line 598 of /lib/filestorage/stored_file.php: call to stored_file->get_imageinfo()
line 1284 of /course/renderer.php: call to stored_file->is_valid_image()
line 1359 of /course/renderer.php: call to core_course_renderer->course_overview_files()
line 1223 of /course/renderer.php: call to core_course_renderer->coursecat_coursebox_content()
line 1446 of /course/renderer.php: call to core_course_renderer->coursecat_coursebox()
line 2153 of /course/renderer.php: call to core_course_renderer->coursecat_courses()
line 2452 of /course/renderer.php: call to core_course_renderer->frontpage_available_courses()
line 121 of /index.php: call to core_course_renderer->frontpage()
```

**Comment by danmarsden** [comment]
Thanks @dmitriim - this is a regression from #465 

What happens here is that it tries to recover the missing file in object storage, which fails, so it  then calls the core file api recover file function,
https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/local/store/object_file_system.php#L596

problem is that the core recover file fucntion tries to access the external storage trashdir which now throws an exception - I'm guessing we need to stop throwing an exceptions in get_trash_fullpath_from_hash and just return "false" ? - not ideal, but at least that will prevent the fatal error.

**Comment by dmitriim** [comment]
Thanks @danmarsden I don't fully understand how all this works and what will happen next if get_trash_fullpath_from_hash will return false. From the quick scanning of the code it doesn't look like it will explode anything. 

Pinning @brendanheywood and @golenkovm

**Comment by danmarsden** [comment]
we added the exception because we wanted to find out if anything was still calling it - now that we see what is calling it (and where) I think we should just change to returning fase instead - but Brendan was the one who suggested we add in exceptions there so will leave it for him to decide :-)

**Comment by brendanheywood** [comment]
we should be throwing exceptions because there should not be any code calling it, we should not be shooting the messenger. The whole concept of a trashdir is not part of the public api for the file_system so we just need to keep ripping out more stuff.

I think the correct thing to do here is not call the parent here:

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/local/store/object_file_system.php#L596

**Comment by danmarsden** [comment]
hmm - my concern with that is that it won't check local disk to see if it can be recovered - and it feels weird to re-implement the local disk recovery functions within the object storage plugin. under some config - some files are only stored locally so the local trashdir folder should be checked.

**Comment by brendanheywood** [comment]
Supporting local trashdir is not particular high on our radar, but if its important to you then sure lets do the work to support it. I missed the subtly here and thought the direction we'd gone in was completely removing local trashdir in all cases.

**Comment by danmarsden** [comment]
we've removed object storage trashdir... but... not all files are in object storage right? - so when you call "recover_file" it needs to check both object storage and local disk. First it checks object storage - and says "we don't use trashdir" but it then needs to fallback to local disk check which it does by calling the parent class.. problem is that the parent class doesn't just check local trashdir, it also checks object storage again.

**Comment by brendanheywood** [comment]
Yup agree, we are on the same page now on the problem side. Not 100% what to do on the solution side (not here today and need to run sorry)

**Comment by danmarsden** [comment]
I'm leaning towards throwing a debugging error instead of an exception in the get_trash_fullpath_from_hash() function instead of an exception for now.

**Comment by danmarsden** [comment]
..and then follow up with a moodle tracker to improve the core recover_file function so that we can get it to do local recovery only rather than asking the other file system to do it as well.
