### ISSUE TITLE
Proxy range requests - Test range request failed

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_objectfs#481]
![image](https://user-images.githubusercontent.com/4626431/165436415-0792edce-8b34-45f0-9225-9111b218e93f.png)

This may be related to recent changes in AWS SDK https://github.com/catalyst/moodle-local_aws/pull/36

**Comment by dmitriim** [comment]
Maybe we can add new check for that error  as part of https://github.com/catalyst/moodle-tool_objectfs/issues/480

**Comment by golenkovm** [comment]
This seems to be a regression of https://github.com/catalyst/moodle-tool_objectfs/commit/6594ab564d2bfb56dd8c5c585df17bd69d4eaaea#diff-4e02103ff7f7bb1344e04cad613008c75189e98e553015aacbd2a01f7a913123R464

`$signedurl` used to be string, not moodle url, so `$url` here https://github.com/catalyst/moodle-tool_objectfs/commit/6594ab564d2bfb56dd8c5c585df17bd69d4eaaea#diff-4e02103ff7f7bb1344e04cad613008c75189e98e553015aacbd2a01f7a913123R697 has to be string as well.
