### ISSUE TITLE
Add delete from s3 functionality

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#49]
What needs to happen:

* New admin setting for delete from external storage
* Extend remove_file https://github.com/moodle/moodle/blob/master/lib/filestorage/file_system_filedir.php#L287 to delete properly in the case that new setting is set.
* Add tests
* Update readme - reccomended S3 and azure permissions will need to have delete included for production

**Comment by ilya-catalyst** [comment]
This has been already implemented. Closing
