### ISSUE TITLE
Response code and Content-Length in request to presigned url

### ISSUE THREAD

**Issue by Logiar** [catalyst/moodle-tool_objectfs#491]
https://github.com/catalyst/moodle-tool_objectfs/blob/8357690b705c244f6b7cfc4b039cf4d6e39a8981/classes/local/store/s3/client.php#L759

Sending a response code in the request seems odd, but the thing that struck me the most odd is sending Content-Length based on the range requested when the body of the request is empty. Is this some strange S3 convention or trick I'm not understanding in the code? I suspect this is causing requests to my "s3" provider to time out as they hold the response waiting for a request body that never arrives.

**Comment by brendanheywood** [comment]
That header does seem wrong, and I strongly suspect it is completely ignored by s3. It isn't really even valid syntax for a head.

Content-length on the other hand is a valid request header and it also looks wrong. I suspect it is ignored by s3 but your alternate one is honoring it and waiting. So no magic trick here :)

What provider are you using? pr's welcome

**Comment by Logiar** [comment]
We're using intility, which seems to using NetApp StorageGRID judging from the links they have on the object storage page.
Made a pull request #492

**Comment by brendanheywood** [comment]
thanks @Logiar :)
