### ISSUE TITLE
DB Error on filesize when upgrading 

### ISSUE THREAD

**Issue by nbozhkov-ucl** [catalyst/moodle-tool_objectfs#516]
We are getting the following error when upgrading from 3.11.7 to 3.11.10+ Build: 20220930
[
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/107557440/194019151-5c94f93d-b7a1-43de-8a20-fa02239cf2d0.png)
](url)

Thanks.
Nikola

**Comment by aspark21** [comment]
Came across the same when doing the 4.1 upgrade for https://tracker.moodle.org/browse/MDLQA-17232
https://tracker.moodle.org/secure/attachment/116649/part%206.pdf

Upgrade of objectfs from 2022070400 to 2022070401 is extremely slow and times out a number of times, in addition to the above error. 

Probably going to hold off taking this new version to prod until this has been sorted.

Will log a WRMS ticket to pick up on this

**Comment by aspark21** [comment]
Succeeded on second/third attempt:
2022070401: Success (606.74 seconds)
Success (607.90 seconds)

**Comment by brendanheywood** [comment]
This pr is related to the upgrade speed:

https://github.com/catalyst/moodle-tool_objectfs/pull/518

**Comment by aspark21** [comment]
#518 did fix it for us. 

Thanks!
