### ISSUE TITLE
Fix settings page checkboxes for boost

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#52]
Looks bad:

![toggle_text_issue](https://cloud.githubusercontent.com/assets/17265456/23285274/3b94daa2-fa84-11e6-8b84-64b99a1753d7.png)

**Comment by kenneth-hendricks** [comment]
Also add a disabled if for Maximum task runtime while there

**Comment by kenneth-hendricks** [comment]
May have a look at templating the page for 32 +

**Comment by brendanheywood** [comment]
This might be completely redundant with the move to admin settings

**Comment by gleimermora** [comment]
The settings page has been converted to admin settings.
