### ISSUE TITLE
Test support for 4.1 -> Some issues found

### ISSUE THREAD

**Issue by marxjohnson** [catalyst/moodle-tool_objectfs#523]
I have tested installation, automated tests and signed URL tests on Moodle 4.1. I found the following minor issues:

* The unit test classes need renaming, as PHPUnit has deprecated class name that do not match the file name.
* Test data generator methods are prefixed with `test_` so are run as tests and failing as they make no assertions.
* Some other tests are failing as they make no assertions.
* Unrelated to 4.1 but still worth fixing, some admin settings are missing defaults, causing warnings on the admin screens.
* Some tests assume no files exist by default, so are failing due to incorrect record counts.

**Comment by danmarsden** [comment]
thanks @marxjohnson  - flagging this as closed, as the 4.1 stuff has been merged  - thanks!
