### ISSUE TITLE
tool_objectfs doesn't delete files from S3

### ISSUE THREAD

**Issue by KaterynaLove** [catalyst/moodle-tool_objectfs#533]
I've installed the tool_objectfs plugin together with the local_aws plugin, and configured all the settings. When I upload the files to Moodle and run a cron task to upload those into S3 bucket the files get uploaded successfully. The only issue is that I cannot delete the files from S3 after I run the delete_local_objects task.
What am I missing?

**Comment by danmarsden** [comment]
The delete_local_objects task is not responsible for deleting objects from the "external/s3 bucket" - that task is responsible for deleting files from local storage that have been uploaded to S3 and aren't needed locally anymore.

There are a few different tasks that all work together when dealing with deleting files that are no longer used - you also have Moodle's "Trash-file" handling that can get in the way here.

objectfs has 2 different methods for deleting external files as mentioned in the help text for the "delete external files" settings:

*Delete external file on orphan clean-up - This will delete the external file when the delete orphaned metadata task task runs.
(Note that simply running the "delete orphaned metatdata" task manually once may not be enough - there are various things that occur and it may require all object fs tasks to complete (and it may also need to run more than once) - the code is written in a way to prevent slamming API's and just tick away nicely on large sites, so it's best to test this sort of stuff on a site that is running cron properly (not on a development system that only runs cron tasks manually.)

*Delete completely - this will tell the external storage to delete the file immediately - (use with caution! - if the same file is being uploaded while being deleted issues could occur.) - but this method is probably easier/faster to test with on a local machine.

hope that helps!
