### ISSUE TITLE
Cannot create file 1/tool_objectfs/settings/0/😀.txt

### ISSUE THREAD

**Issue by vegetas940** [catalyst/moodle-tool_objectfs#540]
Moodle 4.1.1 on AWS EC2
Admin tools / Object storage file system / Plugin Settings
After setting AWS S3 configuration, it shows "Cannot create file 1/tool_objectfs/settings/0/😀.txt" and couldn't go to the setting page.
There're several files created in my S3 bucket, so the S3 settings should be right.
Please help! Thank you in advance!

**Comment by aspark21** [comment]
seeing this on 3.9 and objectfs 2021122307
not an issue in 3.11 or 4.1 with objectfs 2022120800 that I can see.
maybe config related?

**Comment by suhaibkn** [comment]
I was facing the same issue. Turns out the issue was not with the plugin, but with my db.

My db collation was not supporting storing Unicode characters.

I was getting the below error when debugging:

```
PHP message: Default exception handler: Cannot create file 1/tool_objectfs/settings/0/😀.txt Debug: Incorrect string value: '\xF0\x9F\x98\x80.t...' for column `dbname`.`mdl_files`.`filename` at row 1
INSERT INTO mdl_files (... ,filename, ...) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
  0 => ...,
  1 => ...,
  ...,
  5 => '😀.txt',
  6 => ...,
  ...,
  17 => ...,
)]
```

I fixed the issue by setting my `dbcollation` to `utf8mb4_unicode_ci` in `config.php` and running

```bash
php admin/cli/mysql_collation.php --collation=utf8mb4_unicode_ci
```

**Comment by vegetas940** [comment]
Thank you both! AS @suhaibkn said, setting dbcollation to utf8mb4_unicode_ci in config.php solved this problem!
