### ISSUE TITLE
Check if there are any pending objects to be stored to storage after running "\tool_objectfs\task\check_objects_location" scheduled task

### ISSUE THREAD

**Issue by NagaSirishaGarapati** [catalyst/moodle-tool_objectfs#573]
The task "\tool_objectfs\task\check_objects_location" add objects and their location to the "mdl_tool_objectfs_objects" table which are newly added/updated.
The task "\tool_objectfs\task\check_objects_location" call "get_object_location_from_hash()" method but in 99% cases it will be 
OBJECT_LOCATION_LOCAL.
So, if the task is not running often enough it may lead to a big number of new files that do not have their location set in the "mdl_tool_objectfs_objects" table.
Thus, it would be good to have a Moodle check for this

Example : 
While a scheduled_task is running on a daily basis and the task is uploading 50k records on a daily basis.
If there are so many files that haven't been stored in storage(s3) 
There must be a check that notifies the user that there are pending objects to be moved to storage.

**Comment by golenkovm** [comment]
After having a closer look it looks like this is not needed anymore. The main issue was fixed in #554
