### ISSUE TITLE
Exception Error on Installing Object Storage File System Plugin on Moodle 4.1 Site

### ISSUE THREAD

**Issue by andisugandi** [catalyst/moodle-tool_objectfs#578]
Dear all,

The installing process of [Object storage file system](https://moodle.org/plugins/download.php/28599/tool_objectfs_moodle41_2023013100.zip) plugin to Moodle 4.1 site as instructed on [Installation page](https://github.com/catalyst/moodle-tool_objectfs#installation), on step number 5 (Install the plugins through the moodle GUI.), resulting the following error:

`Exception - core_plugin_manager::remove_plugin_folder(): Argument #1 ($plugin) must be of type core\plugininfo\base, null given, called in [dirroot]/lib/classes/plugin_manager.php on line 1425`

![moodle-tool_objectfs--remove_plugin_folder-Issue](https://github.com/catalyst/moodle-tool_objectfs/assets/2184391/43c7cbd5-6b12-43cb-8933-d51cd0b797d6)

Kindly need help and guide.

Thank you in advance.

**Comment by Frostist** [comment]
I am running Moodle 4.1.5+ Build: 20230826 and I have php 8.1.2 installed. 

My installation is working.

**Comment by danmarsden** [comment]
That error looks like an issue you might get when trying to install any plugin via the GUI - I expect your server is not configured in a way that allows for plugins to be installed in this manner - try asking for help on the community forums on moodle.org?

**Comment by andisugandi** [comment]
Thank you for the hints.

Does the installation needs also both of the cloned repo (step number 3) and the installation the plugin via GUI / Moodle Admin page (step number 5)?

Screenshot attached.
<img width="1021" alt="ObjectStorage-FS-Plugin-Installation" src="https://github.com/catalyst/moodle-tool_objectfs/assets/2184391/4860388e-38e3-489d-b105-de60434c2cf0">

**Comment by danmarsden** [comment]
If you are using AWS or (S3/Digitalocean) - you will need to install local_aws (and follow it's instructions for install.) - if you are using azure or openstack you will need the other plugins as well (and will need to follow their instructions for install.)

If you haven't installed plugins before or need any help with installing them the best place to ask for help is in the community forums but there is also some further documentation in the moodledocs wiki: https://docs.moodle.org/en/Installing_plugins

good luck!

**Comment by Frostist** [comment]
> Thank you for the hints.
> 
> 
> 
> Does the installation needs also both of the cloned repo (step number 3) and the installation the plugin via GUI / Moodle Admin page (step number 5)?
> 
> 
> 
> Screenshot attached.
> 
> <img width="1021" alt="ObjectStorage-FS-Plugin-Installation" src="https://github.com/catalyst/moodle-tool_objectfs/assets/2184391/4860388e-38e3-489d-b105-de60434c2cf0">
> 
> 

To answer your question. I just installed the plug-in via the GUI portal and also installed the aws plugin via the portal. 

If you don't install via the GUI portal, the tables aren't created in the database.
