### ISSUE TITLE
Inquiry about Moodle 4.3 Compatibility.

### ISSUE THREAD

**Issue by sheetalgulia** [catalyst/moodle-tool_objectfs#595]
Hi there,

I hope this message finds you well. I'm reaching out to inquire about the project's roadmap and whether there are any plans to release a version that is compatible with Moodle 4.3. I appreciate your time and any insights you can provide on this matter.

**Comment by danmarsden** [comment]
Hi @sheetalgulia, 

Feature development and bug fixing across most of our plugins is typically funded by our clients who support our open-source ethos allowing us to share the improvements with the community. We do provide a limited amount of engagement with the community via the moodle.org community forums and welcome pull requests against all our plugins from community members that do not have a contract with us.

We do have a lot of sites using this plugin, and I don't expect it to be long before we release an "official" version that supports 4.3, but we are only able to provide response times/timelines to clients that have a commercial engagement with us through a service level agreement or contract for Moodle services.

What would help us (and the community) would be if you tested the plugin in your latest release and reported any issues you found - that could potentially help speed up the process too!

thanks,
