### ISSUE TITLE
Possibility to include Linode Object Storage

### ISSUE THREAD

**Issue by jimmy0017** [catalyst/moodle-tool_objectfs#604]
I am wondering the possibility to include Linode Object Storage as well?

**Comment by danmarsden** [comment]
@jimmy0017 - it's possible that this plugin works with linode already using the AWS s3 api - at Catalyst our main focus on maintenance and support is for infrastructure we run ourselves for our hosted clients, although feel free to reach out privately if you would like to fund our time to test/confirm/configure the plugin to work with linode.

**Comment by danmarsden** [comment]
I'm closing this as "won't fix" for now, but happy to re-open this if someone wants to fund the development time by our team, or if you want to send us a Pull request for review we'd consider it!

thanks!
