### ISSUE TITLE
Update README core patches to reside in tool_objectfs repo

### ISSUE THREAD

**Issue by kenneth-hendricks** [catalyst/moodle-tool_objectfs#71]
They currently sit at kenneth-hendricks/moodle-fs-api. The patches themselves should sit in the repo for easy application and so that travis can run them as needed. 

See https://github.com/brendanheywood/moodle-local_cleanurls/blob/master/.travis.yml#L46 for another project which implemented this.

**Comment by golenkovm** [comment]
This is fixed in #304 
Hey @kenneth-hendricks phpunit patches are still sitting in your repo.
Could you please postpone deleting of your repo until #292 is fixed.

**Comment by kenneth-hendricks** [comment]
yea no probs
