### ISSUE TITLE
Prefix (S3 Folder) Concern

### ISSUE THREAD

**Issue by WindGroupAdmin** [catalyst/moodle-tool_objectfs#81]
Any place should I watch out after I place the Prefix folder of the S3 bucket?
In term of changing the code?

Thanks

**Comment by kenneth-hendricks** [comment]
Hi @WindGroupAdmin 

I'm not 100% on what you're after here - are you looking to be able to define another folder to hold all the s3 objects within your bucket such that their path becomes like:

S3://{$bucketname}/{$prefixFolder}/{$filePath} ?

If so the place to do so is here:

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/client/s3_client.php#L135

This is definitely a candidate for something that could be configurable via the GUI, so feel free to submit a patch. 

Thanks

**Comment by WindGroupAdmin** [comment]
Hi @kenneth-hendricks 

Yup we added over here. Somehow it affects the cron task for deleting the objects. We will be trying to find out which part that affects that function

**Comment by kenneth-hendricks** [comment]
@WindGroupAdmin 

Ahh i see - the delete task will verify the object is accessible in S3 before it deletes locally - but it doesn't use the full streamwrapper path to do. Instead it uses the path returned here:

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/client/s3_client.php#L156

`return {$prefixFolder}/$l1/$l2/$contenthash`

should do the trick

The previous function i mentioned uses this path as well.

Thanks

**Comment by WindGroupAdmin** [comment]
I created another separate function for it.

Do you think it possible to replace get_fullpath_from_hash with Cloudfront URL instead of S3?

**Comment by kenneth-hendricks** [comment]
To the best of my knowledge the php streamwrapper will not work with cloudfront URLs without custom modification.
