### ISSUE TITLE
Totara support?

### ISSUE THREAD

**Issue by mogul** [catalyst/moodle-tool_objectfs#83]
Hi there,

I'm trying to track down whether it's possible to use S3 for the `sitedata` directory in Totara, as is possible with Moodle's `moodledata` directory using this plug-in.

I didn't think this would be possible as Totara forked from Moodle before v3.3, which added the filesystem API, and there's no reference to it in the Totara docs. However, I noticed that [Totara was referenced in Alex Lawn's post on the Catalyst blog](https://www.catalyst.net.nz/blog/cutting-our-aws-spend-half) about using this plugin to cut Moodle hosting costs, and there are a couple of references to Totara in code and issues here:
https://github.com/catalyst/moodle-tool_objectfs/commit/79aef044c88823ccfd66b39d857e9851b3312892
https://github.com/catalyst/moodle-tool_objectfs/issues/66

Is there is a path to using this plug-in with Totara? If so, where can I find out more about it?

Thanks,
Bret

**Comment by mattporritt** [comment]
Hi Bret,
Yes we use this plugin with both Moodle and Totara, and you are correct that Totara doesn't have the filesystem API support currently in the codebase. To use this plugin with Totara you need to backport the core changes (https://github.com/catalyst/moodle-tool_objectfs#backporting) the same as you would have for pre 3.3 versions of Moodle. 
You can find which version of Moodle your Totara is using by going to 'notifications' from the Totara Admin menu. In the information that is displayed there you will see what version of Moodle your version of Totara is based on. This is true even for Totara 10 (which is based on Moodle 3.2.5).

Hopefully this helps. Catalyst can also provide more in depth paid technical support should you require it.

Matt P

**Comment by mogul** [comment]
Thanks for the detailed answer. This is terrific news! I was checking on behalf a potential customer (a US government agency running Totara) that wants to use cloud.gov. I'll convey this news and make sure they know about your paid support option. Presumably you've got ready-to-go versions of Totara with the backported API in hand?

cloud.gov is based on Cloud Foundry (as is cloud.gov.au), which is very compatible with Heroku... I think if you add all of these terms (Totara, Cloud Foundry and Heroku) to the README.md as well, you'll save people a lot of googling to find this solution.
