### ISSUE TITLE
XMLDB error in 3.5

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-tool_objectfs#85]
I'm seeing the following error, when installing plugin in Moodle 3.5 (pre-release). It looks like a new check in 3.5

``
!!! XML database file errors found !!!
!! Errors found in XMLDB file: PATH attribute does not match file directory: admin/tool/objectfs/db
Error code: ddlxmlfileerror !!
!! Stack trace: * line 352 of /lib/ddl/database_manager.php: ddl_exception thrown
* line 368 of /lib/ddl/database_manager.php: call to database_manager-&gt;load_xmldb_file()
* line 590 of /lib/upgradelib.php: call to database_manager-&gt;install_from_xmldb_file()
* line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
* line 491 of /lib/installlib.php: call to upgrade_noncore()
* line 461 of /lib/phpunit/classes/util.php: call to install_cli_database()
* line 150 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()
``

**Comment by kenneth-hendricks** [comment]
Fixed in https://github.com/catalyst/moodle-tool_objectfs/commit/a5dcb802ec6ec176bfa72421620b4134cbc17f2c
