### ISSUE TITLE
Moodle on Windows is not pushing the data to S3

### ISSUE THREAD

**Issue by nvskarunakar** [catalyst/moodle-tool_objectfs#88]
I have installed Bitnami moodle stack (ver 3.4.x.x) on my Windows 10 machine. I have installed the objectfs and aws plugins in as described in the documentation. The configuration page says "This setting matches $CFG->alternative_file_system_class" and "Could establish connection to the external object storage.". File transfer is enabled, minimum file size for transfers is 10 kb and the minimum age of a file for transfer is set to 1 sec. Please see the attached screenshot.

But no content from moodledata flows from the local disk to S3 bucket. There are no entries in PHP log even though we chose DEVELOPER level logging on Moodle Development Debugging configuration.

Any suggestions on how to enable logs and debug this problem?

Just a tangential questions - do we need CRON daemon to be running on the machine running Moodle for this file transfer to work?

![moodle-s3-plugin](https://user-images.githubusercontent.com/13017461/37286562-45fc6f52-2628-11e8-8f6e-3f08c00b582c.jpg)

thanks,
Karunakar

**Comment by danmarsden** [comment]
Yes - cron is required for this plugin to operate correctly. Cron is also required for many other core moodle functions and is part of the standard install process. All moodle sites(including testing sites) should be configured to trigger cron.

**Comment by nvskarunakar** [comment]
Thanks  Dan! Does it mean that installing Moodle on Windows is practically not possible or not supported?

However, would the plug-in installation process create CRON tasks in crontab on a Linux set up? I appreciate if you confirm this. Does this mean that the Moodle should be run as an administrator on the Linux server?

**Comment by danmarsden** [comment]
This is the wrong place to ask for general moodle installation support. The best place for this is the community forums on moodle.org. the Moodle docs wiki also contains a wide range of guides for installing moodle on different platforms.

Generally most people advise the use of Linux servers to host Moodle but some sites find that it works ok for them to host on Windows.

**Comment by nvskarunakar** [comment]
All right, we will try this plugin on Linux based Moodle.  Thanks for the help.
