### ISSUE TITLE
Moodle proxy setting is ignored

### ISSUE THREAD

**Issue by cristianomariacumer** [catalyst/moodle-tool_objectfs#99]
Hello,

in seems that objectfs is ignoring the proxy setting of the moodle installation. This is problematic if moodle is hosted in a DMZ where egress traffic is not permitted

**Comment by brendanheywood** [comment]
Tasks

* [ ] Have a new admin setting which say wether or not to use the moodle proxy
* [ ] If true the push the moodle proxy settings into guzzle (we could also use the moodle curl lib but I think that is way too much work)
